CREATE TABLE SPPESSOA(
	CODIGO SERIAL NOT NULL,
	NOME VARCHAR(200) NOT NULL,
	CPFCNPJ VARCHAR(200) PRIMARY KEY,
	TELEFONE VARCHAR(60) NOT NULL,
	EMAIL VARCHAR(150) NOT NULL,
	TIPOPESSOA VARCHAR(100) NOT NULL,
	CODUSUARIO INT NOT NULL
);


CREATE TABLE SPUSUARIO(
	CODIGO SERIAL PRIMARY KEY,
	USUARIO VARCHAR(255) NOT NULL,
	SENHA TEXT NOT NULL,
	TIPOUSUARIO VARCHAR(100) NOT NULL
);